version: 2
jobs:
  test:
    docker:
      - image: circleci/golang
        environment:
          GO111MODULE: "ON"
    working_directory: /go/src/github.com/valeska-tech/pantheon
    steps:
      - checkout
      - run: 
          name: test
          command: go test ./... -v -cover -p=1
workflows:
  version: 2
  validate:
    jobs:
      - test