version: 2.1
jobs:
  test:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - run: 
          name: test
          command: go test ./... -v -cover -p=1
workflows:
  version: 2
  validate:
    jobs:
      - test